# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint-commit:
    name: lint (commit)
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: git remote add upstream https://github.com/lux-org/lux
      - run: git fetch upstream
  pre-commit:
    name: Check pre-commit hooks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-client==6.1.6
        pip install wheel
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Test with Pytest and Code Coverage Report
      run: |
        pytest --cov-report term --cov=lux tests/
        bash <(curl -s https://codecov.io/bash)
